version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=user-db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret

    ports:
      - "5432:5432"
